[package]
name = "chord-chart-ts"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
chord-chart = { path = "../chord-chart" }
wasm-bindgen = "0.2.74"
wee_alloc = "0.4.5"

[profile.release]
lto = true
opt-level = "s"
