name: Test Python

on:
  push:
    paths:
      - chord-chart-py/**
    branches:
      - main
  pull_request:
    paths:
      - chord-chart-py/**
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: chord-chart-py

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('chord-chart-py/pyproject.toml') }}
      - run: make install
      - run: make check-types
      - run: make test
