name: Test Python

on:
  push:
    paths:
      - chord-chart-py/**
    branches:
      - main
  pull_request:
    paths:
      - chord-chart-py/**
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: chord-chart-py

jobs:
  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: check-types-${{ hashFiles('chord-chart-py/pyproject.toml') }}
      - run: make install
      - run: make check-types

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.7", "pypy3.8", "pypy3.9"]
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: test-${{ matrix.version}}-${{ hashFiles('chord-chart-py/pyproject.toml') }}
      - run: make install
      - run: make test
